server:
  port: 8086
#  servlet:
#    context-path: /springboot-server
api:
  url: http://localhost:${server.port}
spring:
  application:
    name: ddtrace-server
  mvc:
    view:
      prefix: /
      suffix: .html
  main:
    allow-bean-definition-overriding: true
extra:
  host: localhost
client: true

#logging:
#  config: classpath:log4j2-1.xml
profiling:
  file: /opt/profiling/profiling.txt
