FROM openjdk:8-jdk-alpine

# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp

WORKDIR /data
RUN mkdir logs
# 这个目录自行修改
ADD target/springboot-server.jar app.jar
ADD opentelemetry-javaagent-1.28.0-guance.jar /agent/opentelemetry-agent.jar
ADD guance-java-extension.jar /agent/guance-java-extension.jar
ENV JAVA_TOOL_OPTIONS "-javaagent:/agent/opentelemetry-agent.jar"
# 修改时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 解决中文乱码
ENV LANG en_US.UTF-8
ENV jar app.jar
ENV OTEL_RESOURCE_ATTRIBUTES "service.name=Springboot-server"
ENV OTEL_IMR_EXPORT_INTERVAL "10000"
ENV OTEL_TRACES_EXPORTER "guance"
ENV OTEL_METRICS_EXPORTER "guance"
ENV OTEL_EXPORTER_GUANCE_ENDPOINT "https://openway.guance.com"
ENV OTEL_JAVAAGENT_EXTENSIONS "guance-java-extension.jar"
ENV OTEL_PROPAGATORS "tracecontext,baggage"

ENTRYPOINT ["sh", "-ec", "exec java ${JAVA_OPTS} -jar ${jar} ${PARAMS} 2>&1"]
